baseURL = "http://sarilee.art/"
languageCode = "en"
title = "sarilee"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
color_scheme = "dark" # "light" or "dark"

