[[navbar]]
  identifier = "index"
  name = "トップ"
  url = "/ja-JP/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "彼らは何者か"
  url = "/ja-JP/about/"
  weight = 2
[[navbar]]
  identifier = "contact"
  name = "コンタクト"
  url = "/ja-JP/contact/"
  weight = 3
[[navbar]]
  identifier = "gallery"
  name = "ギャラリー"
  url = "/ja-JP/gallery/"
  weight = 4