[[navbar]]
  identifier = "index"
  name = "Home"
  url = "/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
[[navbar]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 3
[[navbar]]
  identifier = "gallery"
  name = "Gallery"
  url = "/gallery/"
  weight = 4