[[navbar]]
  identifier = "index"
  name = "主页"
  url = "/zh-CN/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "关于我"
  url = "/zh-CN/about/"
  weight = 2
[[navbar]]
  identifier = "contact"
  name = "联系"
  url = "/zh-CN/contact/"
  weight = 3
[[navbar]]
  identifier = "gallery"
  name = "图集"
  url = "/zh-CN/gallery/"
  weight = 4
