[[navbar]]
  identifier = "index"
  name = "Home"
  url = "/de-DE/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "Wer ich bin"
  url = "/de-DE/about/"
  weight = 2
[[navbar]]
  identifier = "contact"
  name = "Kontakt"
  url = "/de-DE/contact/"
  weight = 3
[[navbar]]
  identifier = "gallery"
  name = "Galerie"
  url = "/de-DE/gallery/"
  weight = 4
