[[navbar]]
  identifier = "index"
  name = "Home"
  url = "/it-IT/"
  weight = 1
[[navbar]]
  identifier = "about"
  name = "Chi Sono"
  url = "/it-IT/about/"
  weight = 2
[[navbar]]
  identifier = "contact"
  name = "Contatto"
  url = "/it-IT/contact/"
  weight = 3
[[navbar]]
  identifier = "gallery"
  name = "Galleria"
  url = "/it-IT/gallery/"
  weight = 4
